# Minimal Kubernetes deployment for TicTac Online
# Single file with all necessary resources
---
apiVersion: v1
kind: Namespace
metadata:
  name: tictac
---
# Core configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: tictac-config
  namespace: tictac
data:
  DATABASE_URL: "ws://surrealdb:8000"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  VITE_API_URL: "http://localhost:8080"  # For client build (using port-forward)
  # CORS configuration - comma-separated list of allowed origins
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080"
---
# Secrets for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: tictac-secret
  namespace: tictac
type: Opaque
stringData:
  JWT_SECRET: "your-secret-key-change-in-production"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "adminpass"
---
# PersistentVolumeClaim for SurrealDB data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb-data
  namespace: tictac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# SurrealDB Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
  namespace: tictac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: surrealdb
  template:
    metadata:
      labels:
        app: surrealdb
    spec:
      containers:
      - name: surrealdb
        image: docker.io/surrealdb/surrealdb:v2.3.7
        args: ["start", "--user=root", "--pass=root", "file:/data/database.db"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: surrealdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
  namespace: tictac
spec:
  selector:
    app: surrealdb
  ports:
  - port: 8000
---
# Backend Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: tictac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z surrealdb 8000; do echo waiting for db; sleep 2; done']
      containers:
      - name: server
        image: localhost/tictac-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: tictac-config
        - secretRef:
            name: tictac-secret
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: tictac
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 8080
    nodePort: 30080
---
# Frontend Client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: tictac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: localhost/tictac-client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: VITE_API_URL
          value: "http://localhost:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: tictac
spec:
  type: NodePort
  selector:
    app: client
  ports:
  - port: 3000
    nodePort: 30030